
name: Deploy Infra

on:
  push:
    branches: 
      - master
    paths:
      - 'projects/infra/**'
      - '.github/workflows/deploy-infra.yml'

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install dependencies
        run: yarn --frozen-lockfile
