
name: Lint
on: [push]

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install dependencies
        run: yarn --frozen-lockfile

      - name: lints
        run: yarn eslint .

      - name: next lints
        run: yarn lint
